---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	parser(parser)
	summarizer(summarizer)
	storyboarder(storyboarder)
	run_scene(run_scene)
	concat(concat)
	emb_consolidate(emb_consolidate)
	__end__([<p>__end__</p>]):::last
	__start__ --> parser;
	parser -. &nbsp;END&nbsp; .-> __end__;
	parser -. &nbsp;next&nbsp; .-> summarizer;
	summarizer -. &nbsp;END&nbsp; .-> __end__;
	summarizer -. &nbsp;next&nbsp; .-> storyboarder;
	storyboarder -. &nbsp;END&nbsp; .-> __end__;
	storyboarder -. &nbsp;Send x N&nbsp; .-> run_scene;
	run_scene --> concat;
	concat --> emb_consolidate;
	emb_consolidate --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
